imie=str(input("podaj imie: "))
nazwisko=str(input("podaj nazwisko: "))
wiek=int(input("podaj wiek: "))
print(f"witaj {imie}")
print(f"Twój wiek to: {wiek}")
inicjaly= imie[0].upper()+nazwisko[0].upper()
print(f"twoje incjały to: {inicjaly}")
lancuch=str(input("podaj łancuch znaków: "))
print((f'{lancuch} ')*5)
lancuch1= str(input("podaj lanuch1/2: "))
lancuch2= str(input("podaj lanuch2/2: "))
print(lancuch1+lancuch2)
lancuch3= lancuch1[:len(lancuch1)//2]+lancuch2[:len(lancuch2)//2]
print(lancuch3)